### ISSUE TITLE
KestralMock not working with Refit

### ISSUE THREAD

**Issue by gurmeetsg** [JasonRowe/KestrelMock#1]
In my application, i call various Rest endpoints using a third party framework called Refit
https://github.com/reactiveui/refit

When i try to mock that api using KestralMock , Upon execution the api call remains in the 
Result = "Not Yet Computed" and status "WaitingForActivation" state 
and hence the code throws an exception when trying to retrieve the response data.

Where as if i try to create an HttpClient  similar to samples given in your code it works .

**Comment by gurmeetsg** [comment]
Any Updates on this ??

**Comment by JasonRowe** [comment]
A recent change to return a status code was added if you want to retest. I'll also try to take a look.

**Comment by JasonRowe** [comment]
Added a test using refit and it seems to work now.
