### ISSUE TITLE
Automatic swagger/swashbuckle generation

### ISSUE THREAD

**Issue by jkone27** [JasonRowe/KestrelMock#13]
Would be very cool to display a **dynamic** swagger/swashbuckle (openapi) page based on currently configured **appsettings.json**, quite challenging but would be awesome 

https://docs.microsoft.com/en-us/samples/aspnet/aspnetcore.docs/getstarted-swashbuckle-aspnetcore/?tabs=visual-studio

idea for improvement 👍

**Comment by JasonRowe** [comment]
Wow that is a cool idea. I only know of the swagger configuration file that is generated from controllers. I wonder if this type of on the fly configuration is supported by swagger.

**Comment by jkone27** [comment]
we could use this: https://github.com/microsoft/OpenAPI.NET, and write to a file which we can just exposes in the expected swagger route .e.g 
```/swagger/v2/swagger.json``` 
or similar.
Used by swashbuckle to present the UI

**Comment by JasonRowe** [comment]
I think some of the mock endpoints might be tricky to represent the path object in the OpenAPI specification 

http://spec.openapis.org/oas/v3.0.3#pathsObject

Possibly could use path templating or leave some blank and just fill in the description.

**Comment by JasonRowe** [comment]
Closing these out now that they are years old
