### ISSUE TITLE
implement HTTP verb

### ISSUE THREAD

**Issue by jkone27** [JasonRowe/KestrelMock#14]
a resource accepts different http verb, seems we are providing verbs but they are not actually used for resources, e.g. the verb is ignore (both GET, DELETE or PUT will work the same)

the verb is already in the configuration object, but does not currently seem to work as expected,
also for different verbs on a same resource/path

**Comment by bigtfromaz** [comment]
I want to second the motion on this one.  There seems to be no way to Mock a different response for GET and POST.  I would classify this as a bug.

**Comment by jkone27** [comment]
mm that's unfortunate, yes it can be probably labeled as bug agree. 
off-topic: I noticed also some different behaviours after my last PR, i will try to add some integration test coverage as soon as i have some free dev time. Have a nice day 👍

**Comment by JasonRowe** [comment]
@jkone27 @bigtfromaz if either of you have time to do a quick review of my PR I would appreciate it.

https://github.com/JasonRowe/KestrelMock/pull/18
