### ISSUE TITLE
Feature request: json path or similar way of specifying specific field in body re-write

### ISSUE THREAD

**Issue by jkone27** [JasonRowe/KestrelMock#19]
would be nice to be able to specify json path for body rewrites, so that body rewrite can be precise ,
or a similar mechanism

https://jsonpath.com/

https://www.newtonsoft.com/json/help/html/QueryJsonSelectTokenJsonPath.htm

sample body response

```js
{
  'Stores': [
    'Lambton Quay',
    'Willis Street'
  ],
  'Manufacturers': [
    {
      'Name': 'Acme Co',
      'Products': [
        {
          'Name': 'Anvil',
          'Price': 50
        }
      ]
    },
    {
      'Name': 'Contoso',
      'Products': [
        {
          'Name': 'Elbow Grease',
          'Price': 99.95
        },
        {
          'Name': 'Headlight Fluid',
          'Price': 4
        }
      ]
    }
  ]
}
```

and e.g. in the mock settings have

```js
"Replace": {
          "UriTemplate": "test/{store}/{productName}",
          "UriJsonPathReplacements": {
            "$.Stores[0]": "{store}", //bodyValue: uriValue
            "$.Manufacturers[1].Products[0].Name": "{productName}"
          }
        }
```

**Comment by StefH** [comment]
Hello @jkone27, you could also take a look at another dotnet Mocking tool : **WireMock.Net** which supports response templating: https://github.com/WireMock-Net/WireMock.Net/wiki/Response-Templating what maybe can help you.

**Comment by JasonRowe** [comment]
Closing these out now that they are years old
