### ISSUE TITLE
Docker image to registry

### ISSUE THREAD

**Issue by jkone27** [JasonRowe/KestrelMock#27]
Maybe we could also add the image to registry via this , @JasonRowe  , what do you think about it ?
maybe we also miss a way to add meta-data to the image? not sure

https://github.com/marketplace/actions/build-and-push-docker-images

**Comment by JasonRowe** [comment]
Yeah would be nice to have it automated. Maybe I can do the same with the nuget package

**Comment by JasonRowe** [comment]
Maybe this will push it to github registry?
https://github.com/JasonRowe/KestrelMock/pull/29
