### ISSUE TITLE
published docker image issue

### ISSUE THREAD

**Issue by jkone27** [JasonRowe/KestrelMock#31]
tired to pull and run from dockerhub the image we published, seems to have some problems. couldn't not get the mocked responses. (tried both localhost and 127.0.0.1)

![image](https://user-images.githubusercontent.com/10419217/97113495-13c90980-16eb-11eb-8713-d8039a46cc79.png)

```cli
docker run -p 5006:5000 -e ASPNETCORE_URLS=http://127.0.0.1:5000 jasonrowe/kestrelmock
```

i also tried inspect the image and required configuration files seems to be there (responses folder and appsetting.json),
and server "starts listening to 5000 correctly". Not sure what's wrong

```terminal
Hosting environment: Production

Content root path: /app

Now listening on: http://127.0.0.1:5000

Application started. Press Ctrl+C to shut down.
```

**Comment by JasonRowe** [comment]
When I used a docker file like we have in the readme it worked fine.

**Comment by JasonRowe** [comment]
This works fine

```
docker run -it -p 50000:80 jasonrowe/kestrelmock:latest
```

Then a default test route works http://localhost:50000/starts/with

**Comment by JasonRowe** [comment]
This also works on my machine

```
docker run -p 5006:5000 -e ASPNETCORE_URLS=http://*:5000 jasonrowe/kestrelmock
```

**Comment by jkone27** [comment]
Will try again thanks ! If so we can close it
