### ISSUE TITLE
Add values generators

### ISSUE THREAD

**Issue by jkone27** [JasonRowe/KestrelMock#38]
we want to be able to simply generate random values in response body (and possibly response header fields).
an inspiration could be value placeholders here:
https://marketplace.visualstudio.com/items?itemName=humao.rest-client
(system dynamic variables section)

for example
```
     "myField" : "{{$guid}}"
```

**Comment by JasonRowe** [comment]
Wonder if we could just use https://github.com/moq/Moq.AutoMocker

**Comment by JasonRowe** [comment]
Closing these out now that they are years old
