### ISSUE TITLE
Issue with stream ?

### ISSUE THREAD

**Issue by jkone27** [JasonRowe/KestrelMock#45]
Might be this lines actually close the stream in some context and dont allow further middleware to re-read the stream again eventually 

https://github.com/JasonRowe/KestrelMock/blob/efc1c592b0e9088a850500e1934966480e701e35/KestrelMock/Services/MockService.cs#L76-L80

we might neet to "reqind it" or re-seek to zero or somehow manage to make it readeable again
--> https://github.com/JasonRowe/KestrelMock/pull/46.

**Comment by jkone27** [comment]
also we use a "terminal middleware" 
```
context.Response.WriteAsync(resultBody);
```
which is not very flexible, maybe we should move to something like this instead..
https://andrewlock.net/converting-a-terminal-middleware-to-endpoint-routing-in-aspnetcore-3/

**Comment by jkone27** [comment]
so the use case is when some other middleware tries to access the stream again, it will throw a stream already closed exception. I tried this solution and it works fine in our use case, i will now release and see if it causes any other issues and let you know. but it seems correct to leave it open in my view to allow for customizations further down the middleware pipeline probably.. i am wondering if this has any potential memory impacts, but i suppose not as probably the body stream is handled by aspnet middlware behind the scenes as well

**Comment by JasonRowe** [comment]
KestrelMock.0.5.0-beta.nupkg pushed for testing

**Comment by JasonRowe** [comment]
Included with KestrelMock.0.5.1.nupkg
