### ISSUE TITLE
Add new admin endpoint to view recent requests to mocked endpoints

### ISSUE THREAD

**Issue by JasonRowe** [JasonRowe/KestrelMock#49]
Give a way to view recent requests and the data that was sent to enable more advanced mocking flows.

Original Request:
"With kestrel mock, we've got a use case where our service receives a message, translates and then PUTs to another service ...

So we'd set up a Kestrel Mock to return 200 on the PUT ...

but ideally we want to see that translated data that was made to the PUT ...

Is there a way in Kestrel Mocks to see was was sent to mocked API please?"

**Comment by magicweasel** [comment]
@JasonRowe going to put a guest PR for this shortly.

**Comment by magicweasel** [comment]
@JasonRowe I've got a branch I wanted to push up as a suggestion.

Having difficulty pushing the branch up ...

![image](https://github.com/JasonRowe/KestrelMock/assets/7963468/87c59d80-9f8a-4fe8-80ba-f10cb301ccad)

**Comment by magicweasel** [comment]
@JasonRowe having difficulty pushing up the branch.  Not hugely familiar with github, have you got things locked down so I can't push up a branch or should I be able to?

![image](https://github.com/JasonRowe/KestrelMock/assets/7963468/4cc1e2c1-5691-447a-963a-9d7a3ff40fb6)

**Comment by JasonRowe** [comment]
@magicweasel added to you the repo so you should be able to push a branch now.

**Comment by magicweasel** [comment]
Thanks @JasonRowe, PR up for your approval.

**Comment by JasonRowe** [comment]
resolved via PR #50
