### ISSUE TITLE
improvement proposal: override field in response from request parameters

### ISSUE THREAD

**Issue by jkone27** [JasonRowe/KestrelMock#9]
specify override parameters in json body of response.

**Comment by jkone27** [comment]
https://github.com/JasonRowe/KestrelMock/pull/11 :)

**Comment by jkone27** [comment]
@JasonRowe  do you have time to check this one? :)

**Comment by JasonRowe** [comment]
looking

**Comment by JasonRowe** [comment]
Merged thanks for the great work!
